### ISSUE TITLE
heifsave: Unsupported compression (hevc)

### ISSUE THREAD

**Issue by GrandArth** [libvips/build-win64-mxe#17]
vips-8.10.2-Mon Oct 12 16:43:59 UTC 2020

## Unsupported compression when using hevc
```
PS D:\DESKTOP\vips-dev-8.10\bin> ./vips.exe heifsave 2.jpg 2.heif --compression hevc
heifsave: Unsupported compression
```

In the 8.10.2 build, hevc compression is not usable, while in 8.10.1 it dose.

**Comment by lovell** [comment]
Please see https://github.com/libvips/build-win64-mxe#hevc-related-dependencies

**Comment by GrandArth** [comment]
Oh I see, thx for the info.
I must be blind that i ignored that.
