### ISSUE TITLE
Invalid target specified: "--with-hevc-w64-mingw32.shared.win32.all"

### ISSUE THREAD

**Issue by GrandArth** [libvips/build-win64-mxe#19]
```
------------------------------------------------------------
 Invalid target specified: "--with-hevc-w64-mingw32.shared.win32.all"

 Please use:
 i686-w64-mingw32.static
 i686-w64-mingw32.shared
 x86_64-w64-mingw32.static
 x86_64-w64-mingw32.shared
 armv7-w64-mingw32.static
 armv7-w64-mingw32.shared
 aarch64-w64-mingw32.static
 aarch64-w64-mingw32.shared
------------------------------------------------------------
.  Stop.
```
I was building it with `./build.sh all --with-hevc` and i got above output.
Full output is very clean, but i will attach it anyway.
[log.txt](https://github.com/libvips/build-win64-mxe/files/5830795/log.txt)

**Comment by GrandArth** [comment]
Building with source in 8.10.5 release.

**Comment by kleisauke** [comment]
Indeed, this combination seems to fail. Could you retest with commit https://github.com/libvips/build-win64-mxe/commit/cff83cd752ec9de70151cf871a8bd809a908c1d0?

**Comment by GrandArth** [comment]
Test passed.
Now it can produce correct binary.

**Comment by GrandArth** [comment]
Thx for help.
