### ISSUE TITLE
-dev packages should include headers?

### ISSUE THREAD

**Issue by jcupitt** [libvips/build-win64-mxe#2]
The `-dev` zip that this repo makes only includes the DLLs and EXEs. Many developers will want the headers, the link libraries and the def files too.

Perhaps there should be a switch to generate either a stripped-back binary, or a zip with all the developer files? I could cook up a PR if that would be useful.

**Comment by jcupitt** [comment]
I've done the rc1 in the old jhbuild one. We can switch at any point, I think, so it's not urgent. sharp have their own libvips builder based on jhbuild as well, so it'd be good to pull in anything from that too.

You're right, the vips8 C++ stuff should be in there too. I'm a bit surprised you didn't need the libstdc++ DLL, it's used by some part of libvips as well, I thought. Anyway, more stuff to check.

**Comment by kleisauke** [comment]
I didn't need the `libstdc++-6.dll` because it was only included by `libvipsCC-42.dll` and `libvips-cpp-42.dl`. `libvips-42.dll` (and it's dependencies) doesn't depend on it, see:
![libvips-web-deps](https://user-images.githubusercontent.com/12746591/43518294-e811a65e-958b-11e8-9e50-b340825f3e25.png)
<sup>Checked with the [open-source modern Dependency Walker](https://github.com/lucasg/Dependencies).</sup>

**Comment by jcupitt** [comment]
Nice!

`-O3` enabled the auto-vectoriser. I think with `-Os` you'll need to add `-ftree-vectorize` to enable it. You could consider `-ffast-math` as well.

**Comment by kleisauke** [comment]
The GCC optimizations `-ffast-math` and `-ftree-vectorize` are enabled with the above commit.

Also, thanks for making me a member of the libvips organization, it feels like an honor. Should I move net-vips and this repo to the organization as well?

**Comment by jcupitt** [comment]
Oh, no problem.

Up to you! I can see arguments for having all the bindings in one place, but equally you might prefer to keep your name on them if you want to use them for job hunting. 

I held off from moving libvips into an org for a long time because I hoped having my name on it would help me, so I would completely understand.

**Comment by kleisauke** [comment]
Ah I see, I'll keep my name on the .NET binding for job hunting (I hadn't thought about it, since I'm still a student).

I'll transfer this repo to the libvips organization to make it easier to find and to open up development.

**Comment by kleisauke** [comment]
I'm not sure if the `gtk-docs` still need to be distributed with the binaries. I think most of the developers will check out https://libvips.github.io/libvips/API/current/.

The headers, link libraries and the def files are included in the 8.7+ binaries and I've just updated this distribution to 8.7.1 with https://github.com/libvips/build-win64-mxe/commit/cbd9dabf00989bdb75a1cec1d8b0702ce96e577d.

I'll close this issue. Thanks for noticing this!
