### ISSUE TITLE
Conversion to GIF does not work

### ISSUE THREAD

**Issue by sergeevabc** [libvips/build-win64-mxe#29]
Sources: [vips.exe][1], [in.png][2]

```console
$ ver & vips --version
Microsoft Windows [Version 6.1.7601]    
vips-8.11.0-Wed Jun  9 18:20:35 UTC 2021

$ vips --vips-progress copy in.png out.tif
vips.exe temp-2: 162 x 192 pixels, 2 threads, 162 x 1 tiles, 128 lines in buffer 
vips.exe temp-2: done in 0,0366s                                                 

$ vips copy in.png out.gif
VipsForeignSave: "out.gif" is not a known file format
```

[1]: https://github.com/libvips/build-win64-mxe/releases/download/v8.11.0/vips-dev-w64-all-8.11.0.zip
[2]: https://user-images.githubusercontent.com/373718/122599700-4b136e80-d05e-11eb-991d-b56a595df8aa.png

**Comment by sergeevabc** [comment]
Alright, I have found a stumbling block. In the past I extracted and used only the contents of `\bin\` whereas the rest of the package turns out to be necessary as well. Could you tell me exactly which files should be moved to `\bin\` to make the app work as expected? I don't want to carry out all that dead weight such as `\include\`  

```
$ vips --vips-progress copy in.png out.gif     
vips.exe temp-1: 162 x 192 pixels, 2 threads, 162 x 1 tiles, 128 lines in buffer 
vips.exe temp-1: done in 0,00799s                                                
```

**Comment by kleisauke** [comment]
Since v8.11.0 some dependencies were built as dynamic loadable module within the "all" variant:
```powershell
PS> .\vips.exe --vips-config | Select-String "dynamic module: yes"
JXL load/save with libjxl: yes (dynamic module: yes)
PDF load with poppler-glib: yes (dynamic module: yes)
slide load with OpenSlide: yes (dynamic module: yes)
Magick package: MagickCore (dynamic module: yes)
```

`gifsave` is using ImageMagick, so you'll need to copy `lib/vips-modules-8.11/vips-magick.dll` with the directory structure being preserved. See the [release notes](https://libvips.github.io/libvips/2021/06/04/What's-new-in-8.11.html#loadable-modules-for-some-dependencies) for more information.

**Comment by sergeevabc** [comment]
Thank you, it works now.
I see why modules are placed outside of bin from dev's pov, but from user's pov who wants portability that is a pain.

**Comment by kleisauke** [comment]
fwiw, the next version will probably place (and search for) the dynamic modules in the `bin/vips-modules-[major].[minor]` directory instead. See commit https://github.com/libvips/build-win64-mxe/commit/365870359dde8c7b971617d348ae8de41f5f690f for more info.
