### ISSUE TITLE
Use specific branch of openslide

### ISSUE THREAD

**Issue by Austinkf** [libvips/build-win64-mxe#48]
I am needing to use a pull request branch of openslide to build with vips because it fixes issues with the BIF ventana image format. I can't figure out a way to change the openslide that is used in the openslide.mk file. Is it possible to use a specific branch of openslide, or is that a limitation to the build tool?

**Comment by kleisauke** [comment]
Looking at the openslide PRs, I assume you wanted to test PR https://github.com/openslide/openslide/pull/395? I had a quick go with commit https://github.com/libvips/build-win64-mxe/commit/216b619cb2a03bf5a656e1eca68530876167153b and it seems to build.

To build locally, you can use:
```bash
$ git clone -b openslide-pr-395 https://github.com/libvips/build-win64-mxe.git
$ cd build-win64-mxe/
$ ./build.sh all x86_64 shared
```

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
