### ISSUE TITLE
issues with Zlib while building libvips

### ISSUE THREAD

**Issue by euzada** [libvips/build-win64-mxe#53]
Hi @kleisauke and @jcupitt, 

I configured docker, wsl2 (Ubuntu) correctly, but when I tried to build libvips, I got an error regarding zlib library (Download failed).

here is a copy of the error about zlib, as you see below. I checked zlib release, and the newer version is 1.3, as you can see here : [zlib](https://github.com/madler/zlib/releases). Will you please help me solve the download issues?:

```What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview
Skip cloning, MXE already exists at /data/mxe
[ignore settings.mk]
[download]    zlib-1.2.13.tar.xz
MXE Warning! Downloading zlib from second URL.
MXE Warning! Downloading zlib from backup.

Download failed or wrong checksum of package zlib!
------------------------------------------------------------
2023-09-15 12:51:53 ERROR 404: Not Found.
--2023-09-15 12:51:53--  http://d1yihgixbnrglp.cloudfront.net/zlib%2D1%2E2%2E13%2Etar%2Exz_d14c38e313afc35a9a8760dadf26042f51ea0f5d154b0630a31da0540107fb98
Reusing existing connection to d1yihgixbnrglp.cloudfront.net:80.
HTTP request sent, awaiting response... 404 Not Found
2023-09-15 12:51:53 ERROR 404: Not Found.
Download failed!
------------------------------------------------------------
[log]      /data/mxe/log/zlib-download

make: *** [Makefile:741: download-only-zlib-1.2.13.tar.xz] Error 1

**Comment by lovell** [comment]
This relates to https://github.com/mxe/mxe/issues/3006 - we're likely to be updating dependency versions in this repo over the new few days.

**Comment by kleisauke** [comment]
I'm currently doing a test build with commit f9a56b57bd1eded028cf3ca862683d5a841334e4, which should fix this.

**Comment by euzada** [comment]
Try it and get pixman error, which also need to be changed.

```[download]    pixman-0.42.2.tar.gz
MXE Warning! Downloading pixman from second URL.
MXE Warning! Downloading pixman from backup.

Download failed or wrong checksum of package pixman!
------------------------------------------------------------
2023-09-15 21:08:32 ERROR 404: Not Found.
--2023-09-15 21:08:32--  http://d1yihgixbnrglp.cloudfront.net/pixman%2D0%2E42%2E2%2Etar%2Egz
Reusing existing connection to d1yihgixbnrglp.cloudfront.net:80.
HTTP request sent, awaiting response... 404 Not Found
2023-09-15 21:08:32 ERROR 404: Not Found.
Download failed!
------------------------------------------------------------
[log]      /data/mxe/log/pixman-download

make: *** [Makefile:743: download-only-pixman-0.42.2.tar.gz] Error 1

**Comment by kleisauke** [comment]
@euzada Both URLs are functional on my end. As as workaround, you could place `pixman-0.42.2.tar.gz` into the `build/mxe/pkg` directory, assuming that the SHA256 checksum matches.
https://github.com/libvips/build-win64-mxe/blob/56e617244d540ec0b4a3333f703ca1a379ecc9cc/build/overrides.mk#L131

**Comment by euzada** [comment]
You are right. The problem is in my network at work. Our IT blocks some links. So, I replaced all the blocked URLs with equivalent ones and the build was successful. 

I wonder if I can use the container and the extra libraries and add libgtk-dev to try to build vipsdisp for Windows. Do you have any recommendations on how or if it is feasible? Because I believe the only extra library I need to add is only related to GTK4, but I could be wrong.

So I can close this issues after your answer or open another one.

**Comment by kleisauke** [comment]
Indeed, the only dependency that is extra needed by vipsdisp is GTK 4. I'm uncertain about the effort required to incorporate this into this build system.
