### ISSUE TITLE
Failed to build package librsvg for target x86_64-w64-mingw32.shared.win32.all!

### ISSUE THREAD

**Issue by euzada** [libvips/build-win64-mxe#54]
Hi,

I am trying to build libvips for windows --without-llvm and as soon as I reach librsvg it failed. Any idea why?

```[build]       librsvg                 x86_64-w64-mingw32.shared.win32.all

Failed to build package librsvg for target x86_64-w64-mingw32.shared.win32.all!
------------------------------------------------------------
checking for dlopen in -ldl... no
checking for x86_64-w64-mingw32.shared.win32.all-cargo... x86_64-w64-mingw32.shared.win32.all-cargo
checking for x86_64-w64-mingw32.shared.win32.all-rustc... x86_64-w64-mingw32.shared.win32.all-rustc
configure: error: librsvg needs at least rustc version 1.70.0
make[1]: *** [Makefile:914: build-only-librsvg_x86_64-w64-mingw32.shared.win32.all] Error 1
make[1]: Leaving directory '/data/mxe'
real    0m2.718s
user    0m2.615s
sys     0m0.186s
------------------------------------------------------------
[log]      /data/mxe/log/librsvg_x86_64-w64-mingw32.shared.win32.all

make: *** [Makefile:902: /data/mxe/usr/x86_64-w64-mingw32.shared.win32.all/installed/librsvg] Error 1`

**Comment by euzada** [comment]
> `--without-llvm` is a untested territory and I would like to remove this option in the near future (see e.g. commit [98bac4a](https://github.com/libvips/build-win64-mxe/commit/98bac4aa496305294149889510cc3d119e64b7a4)).
> 
> Having said that, it looks like librsvg requires Rust 1.70.0, I think commit [448ae0e](https://github.com/libvips/build-win64-mxe/commit/448ae0ede37d6ef0e99690d9237bb9d36ea14989) would fix this.

Thank you for your answer. GCC will be then completly removed. I will test the version with rsut 1.70 and will let you know.

Regards,

**Comment by kleisauke** [comment]
I hope this information helped. Please feel free to re-open if questions remain.
