### ISSUE TITLE
Add `--with-jpegli`

### ISSUE THREAD

**Issue by jcupitt** [libvips/build-win64-mxe#59]
libjxl 0.10.1 includes a new library, jpegli, which is compatible with the standard libjpeg ABI. It uses the libjxl compression machinery to make JPEG files roughly as small as mozjpeg, but at lower CPU cost.

We could have a  `--with-jpegli` option which used that instead of mozjpeg for builds which also included libjxl.

See https://github.com/libvips/libvips/issues/3872

**Comment by kleisauke** [comment]
Implemented with commit 69e2b152b47a319a655d6d177abe82a45371c515.

**Comment by suphamster** [comment]
I assume jpegli is not included in [vips-dev-w64-all-8.15.2.zip](https://github.com/libvips/build-win64-mxe/releases/download/v8.15.2/vips-dev-w64-all-8.15.2.zip) and if so then can you include it in next libvips build, please?
