### ISSUE TITLE
just question on "how to build"?

### ISSUE THREAD

**Issue by lomolomo2** [libvips/build-win64-mxe#62]
I tried docker on Windows with WSL ubuntu, but failed.
Docker image seems build successful. But run it will meet this error:

ERROR: OCI-compliant container runtime not found. Please install Podman or Docker.

Anyone know something?

**Comment by lomolomo2** [comment]
below is my script to run the docker. 
OS: Windows + Docker Desktop + WSL Ubuntu. 
And build the docker image inside the WSL and also run below script inside the WSL.

> #!/usr/bin/env bash
> 
> CUR_DIR=$PWD
> 
> IMAGE_NAME="vips_image"                 
> TAG="latest"   
> 
> docker run --rm -it --name build_vips_container \
>  -v /$PWD:/data ${IMAGE_NAME}:${TAG}

**Comment by lovell** [comment]
This looks like a problem relating to the installation of Docker rather than anything specific to this repo so you may want to seek help on a more general programming site such as StackOverflow or similar.

**Comment by lomolomo2** [comment]
This issue I just solved. But meet the new issue. Let me close this and create new issue.
