### ISSUE TITLE
Can't download ImageMagick

### ISSUE THREAD

**Issue by ashie** [libvips/build-win64-mxe#7]
```
[download]    ImageMagick-6.9.10-35.tar.xz
MXE Warning! Downloading imagemagick from second URL.
MXE Warning! Downloading imagemagick from backup.

Download failed or wrong checksum of package imagemagick!
------------------------------------------------------------
2019-04-05 03:41:21 ERROR 404: Not Found.
--2019-04-05 03:41:21--  http://d1yihgixbnrglp.cloudfront.net/ImageMagick%2D6%2E9%2E10%2D35%2Etar%2Exz_0fbde13bac477fa9f87b5f65a03d99d184167dc7b43ec434b647f024627087d5
Reusing existing connection to d1yihgixbnrglp.cloudfront.net:80.
HTTP request sent, awaiting response... 404 Not Found
2019-04-05 03:41:21 ERROR 404: Not Found.
Download failed!
```

**Comment by kleisauke** [comment]
It seems that ImageMagick has removed another tarball (they remove older versions on their website). I've updated ImageMagick to 6.9.10-37 with 20e562d61095690c8a2235793584164343ea412a. Perhaps I should look for a proper mirror (which doesn't remove the tarballs) to prevent this in the future.

With the above commit (20e562d61095690c8a2235793584164343ea412a), I've also updated the default target to the `web` variant of libvips, which is not dependent on ImageMagick.

By the way,
I can create a `librsvg`-only build  on a separate branch, if you like. It may help to solve https://gitlab.gnome.org/GNOME/librsvg/issues/239.

**Comment by ashie** [comment]
> By the way,
> I can create a `librsvg`-only build on a separate branch, if you like. It may help to solve https://gitlab.gnome.org/GNOME/librsvg/issues/239.

Thank you for your kindness :smile: 

But I choose to modify MXE directly to lean it, and clarify the changes for librsvg:

* https://github.com/mxe/mxe/compare/master...ashie:librsvg-with-rust?expand=1

Again, thank you for your help!
